server:
  port: "8888"
  users:
    # Symmetric encryption user
    - username: "admin"
      password: "admin123"
      # encryption_key: "bXlzZWNyZXRrZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDE="  # base64 random bytes
      encryption_key: 'mgZSpvHRFID43Xf7YwT9NAqYEZc1bgh6P4+U0IOtaueJnkUb0ucRg5Ur8rvzYN46'
      directory: '/mnt/portdata/tmp/configfiles'
      backend: 'filesystem' # file system or git or auto; if auto then auto detect the directory to see if it is git or pure file system and select

    # Asymmetric encryption user (no encryption_key means use RSA)
    - username: "secure"
      password: "secure123"
      key: "/path/to/private.pem"   # RSA private key
      cert: "/path/to/public.pem"   # RSA public key or certificate
      directory: '/path/to/config/files'
      backend: 'filesystem' # file system or git or auto; if auto then auto detect the directory to see if it is git or pure file system and


# Backend configuration organized by backend type
backend_config:
  # Filesystem backend configuration
  filesystem:
    directories:
      - directory: "/mnt/portdata/tmp/configfiles"

  # Git backend configuration
  git:
    uri: "https://github.com/myorg/config-repo.git"
    search_paths: "/,/configs,/application-configs"  # comma-separated
    username: "git-user"           # optional for private repos
    password: "git-token"          # optional for private repos
    default_label: "main"          # default branch/tag
    clone_on_start: true
    local_repo: "./git-repo"       # local clone directory