server:
  port: ${SERVER_PORT:-7777}
  ssl:
    enable: false
    key: /path/to/private/keyfile
    cert: /path/to/certfile
  users:
    # User 1: Filesystem backend
    - username: ${USER1_USERNAME}
      password: ${USER1_PASSWORD}
      encryption_key: ${USER1_ENCRYPTION_KEY}
      directory: ${USER1_DIRECTORY}
      backend: filesystem

    # User 2: PostgreSQL backend
    - username: ${USER2_USERNAME}
      password: ${USER2_PASSWORD}
      encryption_key: ${USER2_ENCRYPTION_KEY}
      backend: postgres

backend_config:
  filesystem:
    directories:
      - ${USER1_DIRECTORY}

  git:
    url: http://etc.com

  postgres:
    default_connection_string: "postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT:-5432}/${DATABASE_NAME}?sslmode=disable"
