name: configserver-dev

services:
  postgres:
    image: postgres:18-alpine
    container_name: config-server-postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER:-configuser}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-configpass}
      POSTGRES_DB: ${DATABASE_NAME:-configdb}
    #ports:
    #  - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-configuser} -d ${DATABASE_NAME:-configdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - config-network

  configservergo:
    build: .
    container_name: config-server-go
    ports:
      - "7777:7777"
    env_file: .env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER:-configuser}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-configpass}
      - DATABASE_NAME=${DATABASE_NAME:-configdb}
    volumes:
      - ./config_data/user1:/data/config/user1
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - config-network

volumes:
  postgres_data:
    driver: local

networks:
  config-network:
    driver: bridge
