package main

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/joho/godotenv"
	u "github.com/sunshine69/golang-tools/utils"
	httpSwagger "github.com/swaggo/http-swagger"

	// "github.com/swaggo/http-swagger"
	"gopkg.in/yaml.v3"

	"configservergo/backend"

	// swagger docs generated by swaggo/swag
	_ "configservergo/docs"
	lib "configservergo/lib"
)

func init() {
	_ = godotenv.Load()
}

type Config struct {
	Server        ServerConfig     `yaml:"server"`
	BackendConfig BackendConfigMap `yaml:"backend_config"`
}

type ServerConfig struct {
	Port  int          `yaml:"port"`
	Ssl   SslConfig    `yaml:"ssl"`
	Users []UserConfig `yaml:"users"`
}

type UserConfig struct {
	Username      string                     `yaml:"username"`
	Password      string                     `yaml:"password"`
	EncryptionKey string                     `yaml:"encryption_key"`
	Directory     string                     `yaml:"directory"`
	Backend       string                     `yaml:"backend"`
	Postgres      backend.PostgresUserConfig `yaml:"postgres"`
}

// UserBackend satisfies backend.UserBackend.
func (u *UserConfig) GetUsername() string      { return u.Username }
func (u *UserConfig) GetBackend() string       { return u.Backend }
func (u *UserConfig) GetPostgresDSN() string   { return u.Postgres.ConnectionString }
func (u *UserConfig) GetPostgresTable() string { return u.Postgres.TableName }

type BackendConfigMap struct {
	FileSystem FileSystemConfig              `yaml:"filesystem"`
	Git        GitConfig                     `yaml:"git"`
	Postgres   backend.PostgresBackendConfig `yaml:"postgres"`
}

type SslConfig struct {
	Enabled bool   `yaml:"enable"`
	Key     string `yaml:"key"`
	Cert    string `yaml:"cert"`
}

type FileSystemConfig struct {
	Directories []string `yaml:"directories"`
}

type GitConfig struct {
	Url string `yaml:"url"`
}

// Response structures for the GetValues endpoint.
type GetValuesResponse struct {
	Name            string           `json:"name"`
	Profiles        []string         `json:"profiles"`
	Label           *string          `json:"label"`
	Version         *string          `json:"version"`
	State           *string          `json:"state"`
	PropertySources []PropertySource `json:"propertySources"`
}

type PropertySource struct {
	Name   string                 `json:"name"`
	Source map[string]interface{} `json:"source"`
}

// ErrorResponse represents a standard error response.
type ErrorResponse struct {
	Description string `json:"description"`
	Status      string `json:"status"`
}

// App holds all dependencies for the HTTP server.
type App struct {
	Users       map[string]*UserConfig
	Backend     *backend.Resolver
	PathServing lib.PathServingConfig
}

var (
	users      = make(map[string]*UserConfig)
	configFile = flag.String("c", u.Getenv("CONFIG_FILE", "config.yaml"), "Config file to load")
	migrate    = flag.Bool("migrate", true, "Run database migrations at startup")
)

func LoadConfig() Config {
	contentb := u.Must(os.ReadFile(*configFile))
	expandedContent := backend.ExpandEnvVars(string(contentb))

	var yamlobj Config
	err := yaml.Unmarshal([]byte(expandedContent), &yamlobj)
	if err != nil {
		fmt.Printf("Error parsing config file %s: %v\n", *configFile, err)
		os.Exit(1)
	}
	for _, user := range yamlobj.Server.Users {
		users[user.Username] = &user
	}

	return yamlobj
}

func main() {
	flag.Parse()
	appConfig := LoadConfig()

	// Build backend resolver.
	var fsBackend *backend.FileSystemBackend
	if len(appConfig.BackendConfig.FileSystem.Directories) > 0 {
		fsBackend = backend.NewFileSystemBackend(appConfig.BackendConfig.FileSystem.Directories[0])
	}

	pgBackend := backend.NewPostgresBackend(appConfig.BackendConfig.Postgres.DefaultConnectionString)

	resolver := backend.NewResolver(fsBackend, pgBackend)

	// Initialize path serving configuration (CONFIGSERVER_FILEPATH env var)
	pathServingConfig := lib.NewPathServingConfig()
	if pathServingConfig.Enabled {
		log.Printf("[INFO] Path serving enabled with prefix: %s", pathServingConfig.Prefix)
	}

	app := &App{
		Users:       users,
		Backend:     resolver,
		PathServing: pathServingConfig,
	}

	// Run migrations if requested.
	if *migrate {
		log.Println("[INFO] Running database migrations...")
		if err := migrateDB(appConfig.BackendConfig.Postgres.DefaultConnectionString); err != nil {
			log.Fatalf("[FATAL] Migration failed: %v", err)
		}
		log.Println("[INFO] Migrations complete.")
	}

	serverAddress := fmt.Sprintf(":%d", appConfig.Server.Port)
	if appConfig.Server.Ssl.Enabled {
		fmt.Printf("Starting HTTPS server on :%s\n", serverAddress)
		tlsConfig := &tls.Config{
			MinVersion: tls.VersionTLS12,
			CipherSuites: []uint16{
				tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			},
		}
		server := &http.Server{
			Addr:      serverAddress,
			Handler:   app.Handler(),
			TLSConfig: tlsConfig,
		}
		log.Fatal(server.ListenAndServeTLS(appConfig.Server.Ssl.Cert, appConfig.Server.Ssl.Key))
	} else {
		fmt.Printf("Start server on port %s\n", serverAddress)
		log.Fatal(http.ListenAndServe(serverAddress, app.Handler()))
	}
}

// Handler returns the configured HTTP mux.
func (a *App) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /encrypt", basicAuth(a.encryptHandler))
	mux.HandleFunc("POST /decrypt", basicAuth(a.decryptHandler))
	mux.HandleFunc("POST /upload", basicAuth(a.uploadHandler))
	mux.HandleFunc("DELETE /delete", basicAuth(a.deleteHandler))
	mux.HandleFunc("GET /list", basicAuth(a.listHandler))
	mux.HandleFunc("GET /health", a.healthHandler)
	// Swagger UI
	mux.Handle("GET /swagger/{path...}", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), // This is bloody magic. The path is handled by httpSwagger in a non documented way
		// The load index.html also magic and the html fire JS script call to this endpoint
		// If u want to be served by itself then keep. Otherwise u need to set something listen on that path and service it
		// That is what I dont like this lib but nothing better so far.
	))
	// Path serving: if CONFIGSERVER_FILEPATH is set, intercept requests that match the prefix
	if a.PathServing.Enabled {
		mux.HandleFunc("GET "+a.PathServing.Prefix+"/", a.pathServingHandler)
	}
	mux.HandleFunc("GET /", basicAuth(a.getValuesHandler))
	return mux
}

// RawFileHandler handles requests that match the CONFIGSERVER_FILEPATH path
// prefix. It resolves the backend for the authenticated user and serves the
// file at the computed relative path.
//
// It is invoked after basic auth has already verified the user. The handler
// supports both filesystem and postgres backends transparently through the
// Backend interface.
func RawFileHandler(w http.ResponseWriter, r *http.Request, app *App, be backend.Backend, relPath string) {
	// Validate the relative path to prevent path traversal attacks.
	if !lib.IsValidRelativePath(relPath) {
		http.Error(w, "Invalid path", http.StatusBadRequest)
		return
	}

	data, err := be.GetFileByPath(relPath)
	if backend.IsNotExist(err) {
		http.Error(w, fmt.Sprintf("File not found: %s", relPath), http.StatusNotFound)
		return
	}
	if err != nil {
		http.Error(w, fmt.Sprintf("Error reading file: %s", err), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/octet-stream")
	w.Write(data)
}

// pathServingHandler handles requests that match the CONFIGSERVER_FILEPATH path prefix.
// It has already been authenticated by basicAuth.
func (a *App) pathServingHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	be, err := a.Backend.ForUser(user)
	if err != nil {
		http.Error(w, fmt.Sprintf("backend error: %s", err), http.StatusBadGateway)
		return
	}

	relPath, ok := a.PathServing.MatchesPath(r.URL.Path)
	if !ok {
		http.Error(w, "Path not found", http.StatusNotFound)
		return
	}

	RawFileHandler(w, r, a, be, relPath)
}

// Process cipher patterns in content.
func processCipherPatterns(content string, user *UserConfig) string {
	return lib.CipherPattern.ReplaceAllStringFunc(content, func(match string) string {
		cipherData := strings.TrimPrefix(strings.TrimSuffix(match, "'"), "'")
		cipherData = strings.TrimPrefix(cipherData, "{cipher}")

		var decrypted string
		var err error

		if user.EncryptionKey != "" {
			// Symmetric encryption
			decrypted, err = u.Decrypt(cipherData, user.EncryptionKey, nil)
		} // TODO support asym decrypt?
		if err != nil {
			fmt.Printf("[ERROR] %s\nData: %s\n", err.Error(), cipherData)
			return "<n/a>"
		}
		return decrypted
	})
}

func basicAuth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		username, password, ok := r.BasicAuth()
		if !ok {
			w.Header().Set("WWW-Authenticate", `Basic realm="ConfigServer Auth"`)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		user, exists := users[username]
		if !exists {
			w.Header().Set("WWW-Authenticate", `Basic realm="ConfigServer Auth"`)
			fmt.Fprintf(os.Stderr, "User '%s' does not exists\n", username)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		if password != user.Password {
			w.Header().Set("WWW-Authenticate", `Basic realm="ConfigServer Auth"`)
			fmt.Fprintln(os.Stderr, "Password not matched")
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		r.Header.Set("X-Username", username)
		next(w, r)
	}
}

// migrateDB runs the CREATE TABLE IF NOT EXISTS migration for the postgres
// backend. Safe to call repeatedly — it is idempotent.
func migrateDB(dsn string) error {
	if dsn == "" {
		return fmt.Errorf("no postgres DSN configured — cannot run migrations")
	}
	pool, err := backend.NewPostgresBackend(dsn).CreateTempPool(dsn)
	if err != nil {
		return err
	}
	defer pool.Close()

	_, err = pool.Exec(context.Background(), backend.TableSQL)
	return err
}

// getValuesHandler processes the Spring Cloud Config GET request.
//
// URL variants supported:
//
//	/{app}-{profile}[-{label}].{ext}          → serve raw file bytes
//	/{app}/{profile}[-{label}]                 → serve as GetValuesResponse
//	/{app}/{profile}/{label}/{path}            → serve raw file by path
//	/{full-file-path-without-ext}              → serve raw file by path
//
// See: https://docs.spring.io/spring-cloud-config/reference/server/serving-plain-text.html
//
// @Summary Retrieve application configuration
// @Description Fetch configuration for a Spring Cloud Config application.
// Supports multiple URL formats:
//   - GET /{app}/{profile} → Returns JSON GetValuesResponse (single profile)
//   - GET /{app}/{profile1},{profile2} → Returns merged JSON with both profiles
//   - GET /{app}/{profile}/{label} → Returns JSON GetValuesResponse with label
//   - GET /{app}/{profile}/{label}/{path} → Returns raw file content by path
//   - GET /{app}-{profile}.{ext} → Returns raw file content
//   - GET /{full-path} → Returns raw file content by path
//
// Profiles are merged in order, with later profiles taking higher priority.
//
// @Tags Config
// @Accept json
// @Produce json
// @Param app path string true "Application name"
// @Param profile path string true "Profile name(s) - comma-separated for multiple profiles"
// @Param label path string false "Git label/branch (optional)"
// @Param path path string false "File path within config (for raw file retrieval)"
// @Param ext path string false "File extension (.yaml, .json, .properties)"
// @Success 200 {object} GetValuesResponse "Configuration data returned as JSON"
// @Success 200 {file} application/octet-stream "Raw file content when requesting .ext format or with Accept: application/octet-stream"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 404 {string} string "Config not found or file not found"
// @Failure 502 {string} string "Backend error"
// @Router /{app}/{profile} [get]
// @Router /{app}/{profile1},{profile2} [get]
// @Router /{app}/{profile}/{label}/{path} [get]
// @Security BasicAuth
func (a *App) getValuesHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	be, err := a.Backend.ForUser(user)
	if err != nil {
		http.Error(w, fmt.Sprintf("backend error: %s", err), http.StatusBadGateway)
		return
	}

	path := r.URL.Path
	paths := strings.Split(path, "/")[1:] // first element is empty because path starts with /
	pathsLen := len(paths)

	// Check if client requests raw content via Accept header
	acceptsRawContent := strings.Contains(r.Header.Get("Accept"), "application/octet-stream")

	switch {
	case pathsLen == 1:
		// Check if single path segment contains hyphen (app-profile format)
		if idx := strings.Index(paths[0], "-"); idx > 0 {
			app := paths[0][:idx]
			profile := paths[0][idx+1:]

			// Check if path ends with supported extension (raw file retrieval)
			ext := filepath.Ext(profile)
			if ext != "" && lib.SupportedFileExtension(ext) {
				// Serve raw file
				_, fileExt := lib.SplitProfileAndExt(profile)
				data, err := be.GetFile(app, strings.TrimSuffix(profile, ext), "", fileExt)
				if backend.IsNotExist(err) {
					http.Error(w, "File not found", http.StatusNotFound)
					return
				}
				if err != nil {
					http.Error(w, fmt.Sprintf("Error reading file: %s", err), http.StatusInternalServerError)
					return
				}
				w.Header().Set("Content-Type", "application/octet-stream")
				w.Write(data)
				return
			}

			// No extension: serve as JSON GetValuesResponse
			a.serveValues(w, be, user, app, []string{profile}, "")
			return
		}
		serveFile(w, be, paths[0])
		return
	case pathsLen == 2:
		// Check if client wants raw content via Accept header
		if acceptsRawContent {
			// Serve as raw file by path
			filePath := paths[0] + "/" + paths[1]
			serveFile(w, be, filePath)
			return
		}
		profiles := lib.ParseProfiles(paths[1])
		a.serveValues(w, be, user, paths[0], profiles, "")
		return
	case pathsLen == 3:
		// Could be /{app}/{profile}/{label} or /{app}/{profile}/{path}
		label, _ := lib.SplitProfileAndExt(paths[2])
		if acceptsRawContent || strings.Contains(paths[2], ".") {
			// Serve as raw file by path
			filePath := paths[0] + "/" + paths[1] + "/" + paths[2]
			serveFile(w, be, filePath)
			return
		}
		profiles := lib.ParseProfiles(paths[1])
		a.serveValues(w, be, user, paths[0], profiles, label)
		return
	case pathsLen > 3:
		// Multi-segment path: /{app}/{profile}/{label}/{path}
		// Try to serve as a raw file. The last path segment is the filename.
		requestFileName := paths[pathsLen-1]
		serveFile(w, be, requestFileName)
		return
	}
}

// serveFile returns the raw bytes of a file from the backend.
func serveFile(w http.ResponseWriter, be backend.Backend, filename string) {
	data, err := be.GetFileByPath(filename)
	if backend.IsNotExist(err) {
		http.Error(w, "File not found", http.StatusNotFound)
		fmt.Printf("[ERROR] file not found: %s\n", filename)
		return
	}
	if err != nil {
		http.Error(w, "Error reading file", http.StatusInternalServerError)
		fmt.Printf("[ERROR] %s\n", err.Error())
		return
	}
	if _, err := w.Write(data); err != nil {
		http.Error(w, "Error", http.StatusInternalServerError)
		fmt.Printf("[ERROR] Sending data to client - %s\n", err.Error())
		return
	}
}

// hasLabelSources checks if any config files exist for the given label.
func (a *App) hasLabelSources(be backend.Backend, user *UserConfig, app string, profiles []string, label string) bool {
	for _, profile := range profiles {
		p, _ := lib.SplitProfileAndExt(profile)
		for _, ext := range lib.SupportedConfigFileType {
			// Check all 4 source patterns
			if ps := a.fetchPropertySource(be, user, app, p, label, ext); ps != nil {
				return true
			}
			if ps := a.fetchPropertySource(be, user, app, "", label, ext); ps != nil {
				return true
			}
			if ps := a.fetchPropertySource(be, user, "application", p, label, ext); ps != nil {
				return true
			}
			if ps := a.fetchPropertySource(be, user, "application", "", label, ext); ps != nil {
				return true
			}
		}
	}
	return false
}

// findLabelForFallback tries to determine which label to use for fetching
// config when no explicit label is specified. It follows Spring Cloud Config
// Server's default label fallback behavior:
//   1. Try with empty label (standard naming: {app}-{profile}.{ext})
//   2. Try label "main" ({app}-{profile}-main.{ext})
//   3. Try label "master" ({app}-{profile}-master.{ext})
//
// Returns the first label that has any config files.
func (a *App) findLabelForFallback(be backend.Backend, user *UserConfig, app string, profiles []string) string {
	// 1. Try with empty label (no label suffix)
	if a.hasLabelSources(be, user, app, profiles, "") {
		return ""
	}
	// 2. Try "main" branch
	if a.hasLabelSources(be, user, app, profiles, "main") {
		return "main"
	}
	// 3. Try "master" branch (fallback)
	if a.hasLabelSources(be, user, app, profiles, "master") {
		return "master"
	}
	// No files found at all
	return ""
}

// serveValues returns a Spring Cloud Config GetValuesResponse JSON with multi-profile support.
//
// Profiles are processed in order, with later profiles taking higher priority.
// For each profile, files are fetched across ALL supported extensions in precedence order
// (properties > yml > yaml > json) and merged together.
// Multiple profiles are merged together.
// Placeholders (${VAR}) are resolved with environment variables.
// Cipher values ({cipher}...) are decrypted.
//
// Property source resolution follows Spring Cloud Config Server precedence:
//   1. {app}-{profile}.{ext}        (highest precedence)
//   2. {app}.{ext}
//   3. application-{profile}.{ext}
//   4. application.{ext}             (lowest precedence)
//
// Higher-precedence sources are listed earlier in the propertySources array.
//
// Default label fallback: When no label is specified, tries "main" first,
// then falls back to "master" (matches Spring Cloud Config Server behavior).
func (a *App) serveValues(w http.ResponseWriter, be backend.Backend, user *UserConfig, app string, profiles []string, label string) {
	if len(profiles) == 0 {
		http.Error(w, "No profiles specified", http.StatusBadRequest)
		return
	}

	// Default label fallback: if no label specified, use findLabelForFallback
	// which checks empty label first, then "main", then "master".
	var selectedLabel string
	if label != "" {
		selectedLabel = label
	} else {
		selectedLabel = a.findLabelForFallback(be, user, app, profiles)
	}

	responseObj := GetValuesResponse{
		Name:            app,
		Profiles:        profiles,
		Label:           &selectedLabel,
		PropertySources: []PropertySource{},
	}

	allPropertySources := []PropertySource{}
	foundAny := false

	for _, profile := range profiles {
		profile, ext := lib.SplitProfileAndExt(profile)

		extensionsToTry := lib.SupportedConfigFileType
		if ext != "" {
			extensionsToTry = []string{ext}
		}

		// For each extension, fetch ALL matching files in Spring Cloud Config precedence order.
		// The order is: properties > yml > yaml > json.
		for _, fileExt := range extensionsToTry {
			// Collect property sources for this extension in precedence order
			var extPropertySources []PropertySource

			// 1. {app}-{profile}.{ext} (highest precedence)
			if ps := a.fetchPropertySource(be, user, app, profile, selectedLabel, fileExt); ps != nil {
				extPropertySources = append(extPropertySources, *ps)
			}
			// 2. {app}.{ext}
			if ps := a.fetchPropertySource(be, user, app, "", selectedLabel, fileExt); ps != nil {
				extPropertySources = append(extPropertySources, *ps)
			}
			// 3. application-{profile}.{ext}
			if ps := a.fetchPropertySource(be, user, "application", profile, selectedLabel, fileExt); ps != nil {
				extPropertySources = append(extPropertySources, *ps)
			}
			// 4. application.{ext} (lowest precedence)
			if ps := a.fetchPropertySource(be, user, "application", "", selectedLabel, fileExt); ps != nil {
				extPropertySources = append(extPropertySources, *ps)
			}

			if len(extPropertySources) > 0 {
				allPropertySources = append(allPropertySources, extPropertySources...)
				foundAny = true
			}
		}
	}

	if !foundAny {
		http.Error(w, "Config not found", http.StatusNotFound)
		return
	}

	responseObj.PropertySources = append(responseObj.PropertySources, allPropertySources...)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(responseObj)
}

// fetchPropertySource retrieves a single config file from the backend,
// applies cipher decryption and placeholder resolution, parses it into a
// flat key-value map, and returns a PropertySource. Returns nil if the
// file does not exist or encounters a backend error.
func (a *App) fetchPropertySource(be backend.Backend, user *UserConfig, app, profile, label, ext string) *PropertySource {
	data, err := be.GetFile(app, profile, label, ext)
	if backend.IsNotExist(err) {
		return nil
	}
	if err != nil {
		log.Printf("[WARN] backend error for %s-%s-%s.%s: %v", app, profile, label, ext, err)
		return nil
	}

	parsedContent := string(data)
	parsedContent = processCipherPatterns(parsedContent, user)
	parsedContent = lib.ResolvePlaceholders(parsedContent)
	result := lib.ParseConfigData(parsedContent, ext)

	sourceName := lib.DetermineSourceName(be, app, profile, label, ext)
	return &PropertySource{
		Name:   sourceName,
		Source: result,
	}
}

// encryptHandler encrypts plaintext with the authenticated user's key.
//
// @Summary Encrypt a value
// @Description Encrypts the provided plaintext using the authenticated user's encryption key.
// Returns the encrypted string directly in the response body.
//
// @Tags Encryption
// @Accept plain
// @Produce text/plain
// @Param body body string true "Plaintext to encrypt"
// @Success 200 {string} string "Encrypted ciphertext"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 400 {object} ErrorResponse "Bad request - invalid body or encryption failed"
// @Router /encrypt [post]
// @Security BasicAuth
func (a *App) encryptHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]

	content, err := io.ReadAll(r.Body)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Can not read request body", "status": "INVALID"})
		return
	}
	output, err := u.Encrypt(string(content), user.EncryptionKey, nil)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Can not encrypt", "status": "INVALID"})
		return
	}
	w.Write([]byte(output))
}

// decryptHandler decrypts a {cipher} value with the authenticated user's key.
//
// @Summary Decrypt a value
// @Description Decrypts the provided ciphertext using the authenticated user's encryption key.
// Returns the decrypted string directly in the response body.
//
// @Tags Encryption
// @Accept plain
// @Produce text/plain
// @Param body body string true "Ciphertext to decrypt"
// @Success 200 {string} string "Decrypted plaintext"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 400 {object} ErrorResponse "Bad request - invalid body or decryption failed"
// @Router /decrypt [post]
// @Security BasicAuth
func (a *App) decryptHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	content, err := io.ReadAll(r.Body)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Can not read request body", "status": "INVALID"})
		return
	}
	output, err := u.Decrypt(string(content), user.EncryptionKey, nil)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Text not encrypted with this key", "status": "INVALID"})
		return
	}
	w.Write([]byte(output))
}

// deleteHandler allows authenticated users to delete a config file.
//
// Query parameters:
//   - app (required)
//   - profile (required)
//   - label (optional)
//   - ext (required, defaults to .yaml)
//
// @Summary Delete a configuration file
// @Description Delete a configuration file for a specific app, profile, and optional label.
//
// @Tags Config
// @Produce application/json
// @Param app query string true "Application name" minlength(1) maxlength(64)
// @Param profile query string true "Profile name (e.g., dev, prod)" minlength(1) maxlength(64)
// @Param label query string false "Git label/branch" minlength(1) maxlength(64)
// @Param ext query string false "File extension" default(.yaml)
// @Success 200 {object} map[string]interface{} "File deleted successfully"
// @Failure 400 {object} ErrorResponse "Bad request - missing params or invalid input"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 404 {string} string "File not found"
// @Router /delete [delete]
// @Security BasicAuth
func (a *App) deleteHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	if user == nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Unauthorized",
			"status":      "INVALID",
		})
		return
	}

	// Parse query parameters
	app := r.URL.Query().Get("app")
	profile := r.URL.Query().Get("profile")
	label := r.URL.Query().Get("label")
	ext := r.URL.Query().Get("ext")
	if ext == "" {
		ext = ".yaml"
	}

	if app == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Missing required parameter: app",
			"status":      "INVALID",
		})
		return
	}

	if !lib.SupportedFileExtension(ext) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Unsupported file extension: %s", ext),
			"status":      "INVALID",
		})
		return
	}

	if !lib.ValidConfigPathSegment(app) || !lib.ValidConfigPathSegment(profile) || !lib.ValidConfigPathSegment(label) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Invalid app/profile/label. Only alphanumeric, hyphens, and underscores allowed",
			"status":      "INVALID",
		})
		return
	}

	be, err := a.Backend.ForUser(user)
	if err != nil {
		log.Printf("[ERROR] Failed to get backend for user %s: %s\n", user.Username, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadGateway)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Backend error",
			"status":      "INVALID",
		})
		return
	}

	if err := be.DeleteFile(app, profile, label, ext); err != nil {
		if backend.IsNotExist(err) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusNotFound)
			json.NewEncoder(w).Encode(map[string]any{
				"description": "File not found",
				"status":      "NOT_FOUND",
			})
			return
		}
		log.Printf("[ERROR] Failed to delete file for %s-%s-%s.%s: %s\n", app, profile, label, ext, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Failed to delete file: %s", err.Error()),
			"status":      "INVALID",
		})
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]any{
		"description": "File deleted successfully",
		"status":      "OK",
		"app":         app,
		"profile":     profile,
		"label":       label,
		"ext":         ext,
	})
}

// listHandler returns a list of all configuration files for the authenticated user.
//
// @Summary List all configuration files
// @Description Returns a list of all configuration files stored for the authenticated user.
//
// @Tags Config
// @Produce application/json
// @Success 200 {array} backend.Info "List of configuration files"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 502 {string} string "Backend error"
// @Router /list [get]
// @Security BasicAuth
func (a *App) listHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	if user == nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Unauthorized",
			"status":      "INVALID",
		})
		return
	}

	be, err := a.Backend.ForUser(user)
	if err != nil {
		log.Printf("[ERROR] Failed to get backend for user %s: %s\n", user.Username, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadGateway)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Backend error",
			"status":      "INVALID",
		})
		return
	}

	files, err := be.ListFiles()
	if err != nil {
		log.Printf("[ERROR] Failed to list files: %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Failed to list files: %s", err.Error()),
			"status":      "INVALID",
		})
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(files)
}

// uploadHandler allows authenticated users to deploy (store) their own config
// files. The request body is the raw file content.
//
// Supports two URL patterns:
//   - POST /{app}/{profile}.{ext}        — no label
//   - POST /{app}/{profile}-{label}.{ext} — with label
//
// The handler validates app/profile/label to prevent path traversal and only
// accepts supported file extensions.
//
// @Summary Upload configuration file
// @Description Upload a configuration file for a specific app, profile, and optional label.
// The request body must contain the raw file content.
//
// Supported URL patterns:
//   - POST /upload?app={app}&profile={profile}&ext={ext}          — no label
//   - POST /upload?app={app}&profile={profile}&label={label}&ext={ext} — with label
//
// @Tags Config
// @Accept plain
// @Produce application/json
// @Param app query string true "Application name" minlength(1) maxlength(64)
// @Param profile query string true "Profile name (e.g., dev, prod)" minlength(1) maxlength(64)
// @Param label query string false "Git label/branch" minlength(1) maxlength(64)
// @Param ext query string false "File extension (.yaml, .json, .properties)" default(.yaml)
// @Param body body string true "Raw configuration file content"
// @Success 200 {object} map[string]interface{} "File uploaded successfully"
// @Failure 400 {object} ErrorResponse "Bad request - missing params or invalid input"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 403 {object} ErrorResponse "Forbidden - unsupported file extension"
// @Failure 500 {object} ErrorResponse "Internal server error - failed to store file"
// @Router /upload [post]
// @Security BasicAuth
func (a *App) uploadHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	if user == nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Unauthorized",
			"status":      "INVALID",
		})
		return
	}

	// Read the request body (raw file content)
	content, err := io.ReadAll(r.Body)
	if err != nil {
		log.Printf("[ERROR] Failed to read request body: %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Can not read request body",
			"status":      "INVALID",
		})
		return
	}
	defer r.Body.Close()

	// Parse query parameters
	app := r.URL.Query().Get("app")
	profile := r.URL.Query().Get("profile")
	label := r.URL.Query().Get("label")
	virtualPath := r.URL.Query().Get("path")

	if app == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Missing required parameter: app",
			"status":      "INVALID",
		})
		return
	}

	// Determine extension
	ext := r.URL.Query().Get("ext")
	if ext == "" {
		ext = ".yaml" // default
	}

	// Validate app/profile/label (allow empty profile for base-level files like application.yml)
	if !lib.ValidConfigPathSegment(app) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Invalid app segment",
			"status":      "INVALID",
		})
		return
	}
	if profile != "" && !lib.ValidConfigPathSegment(profile) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Invalid profile segment",
			"status":      "INVALID",
		})
		return
	}
	if label != "" && !lib.ValidConfigPathSegment(label) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Invalid label segment",
			"status":      "INVALID",
		})
		return
	}

	// Validate extension
	if !lib.SupportedFileExtension(ext) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Unsupported file extension: %s", ext),
			"status":      "INVALID",
		})
		return
	}

	// Validate virtual path if provided
	if virtualPath != "" {
		if !lib.IsValidRelativePath(virtualPath) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusBadRequest)
			json.NewEncoder(w).Encode(map[string]any{
				"description": "Invalid virtual path. Only alphanumeric, hyphens, underscores, dots, and forward slashes allowed",
				"status":      "INVALID",
			})
			return
		}
	}

	// Get backend for user
	be, err := a.Backend.ForUser(user)
	if err != nil {
		log.Printf("[ERROR] Failed to get backend for user %s: %s\n", user.Username, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadGateway)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Backend error",
			"status":      "INVALID",
		})
		return
	}

	// Store the file — use PutFileWithFullPath when a virtual path is provided,
	// otherwise use PutFile (or default path format if path serving is enabled).
	if virtualPath != "" {
		if err := be.PutFileWithFullPath(app, profile, label, ext, virtualPath, content); err != nil {
			log.Printf("[ERROR] Failed to upload file for %s-%s-%s.%s: %s\n", app, profile, label, ext, err.Error())
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusInternalServerError)
			json.NewEncoder(w).Encode(map[string]any{
				"description": fmt.Sprintf("Failed to upload file: %s", err.Error()),
				"status":      "INVALID",
			})
			return
		}
	} else if a.PathServing.Enabled {
		// No path provided and path serving enabled — use default format
		fullPath := fmt.Sprintf("%s/%s-%s%s", app, app, profile, ext)
		if err := be.PutFileWithFullPath(app, profile, label, ext, fullPath, content); err != nil {
			log.Printf("[ERROR] Failed to upload file for %s-%s-%s.%s: %s\n", app, profile, label, ext, err.Error())
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusInternalServerError)
			json.NewEncoder(w).Encode(map[string]any{
				"description": fmt.Sprintf("Failed to upload file: %s", err.Error()),
				"status":      "INVALID",
			})
			return
		}
	} else {
		if err := be.PutFile(app, profile, label, ext, content); err != nil {
			log.Printf("[ERROR] Failed to upload file for %s-%s-%s.%s: %s\n", app, profile, label, ext, err.Error())
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusInternalServerError)
			json.NewEncoder(w).Encode(map[string]any{
				"description": fmt.Sprintf("Failed to upload file: %s", err.Error()),
				"status":      "INVALID",
			})
			return
		}
	}

	// Success response
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]any{
		"description": "File uploaded successfully",
		"status":      "OK",
		"app":         app,
		"profile":     profile,
		"label":       label,
		"ext":         ext,
	})
}

// healthHandler checks the health status of the server and its backends.
//
// Returns 200 OK if all checks pass, or 503 Service Unavailable if any check fails.
//
// @Summary Server health check
// @Description Checks the health status of the server and its configured backends.
//
// @Tags Health
// @Produce application/json
// @Success 200 {object} map[string]interface{} "Server is healthy"
// @Failure 503 {object} map[string]interface{} "Server is unhealthy"
// @Router /health [get]
func (a *App) healthHandler(w http.ResponseWriter, r *http.Request) {
	health := map[string]interface{}{
		"status": "UP",
		"checks": []map[string]interface{}{},
	}

	// Check backend resolver exists
	if a.Backend != nil {
		check := map[string]interface{}{
			"name":   "backend",
			"status": "UP",
		}
		health["checks"] = append(health["checks"].([]map[string]interface{}), check)
	}

	// Check database connectivity using actual configured DSN from users
	// Try to get the DSN from the first user's postgres config
	var pgDSN string
	for _, user := range a.Users {
		dsn := user.GetPostgresDSN()
		if dsn != "" {
			pgDSN = dsn
			break
		}
	}

	if pgDSN != "" {
		pool, err := backend.NewPostgresBackend(pgDSN).CreateTempPool(pgDSN)
		if err != nil {
			check := map[string]interface{}{
				"name":    "database",
				"status":  "DOWN",
				"details": err.Error(),
			}
			health["checks"] = append(health["checks"].([]map[string]interface{}), check)
			health["status"] = "DOWN"
		} else {
			pool.Close()
			check := map[string]interface{}{
				"name":   "database",
				"status": "UP",
			}
			health["checks"] = append(health["checks"].([]map[string]interface{}), check)
		}
	}

	w.Header().Set("Content-Type", "application/json")
	if health["status"] == "DOWN" {
		w.WriteHeader(http.StatusServiceUnavailable)
	} else {
		w.WriteHeader(http.StatusOK)
	}
	json.NewEncoder(w).Encode(health)
}
