package main

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/joho/godotenv"
	u "github.com/sunshine69/golang-tools/utils"
	httpSwagger "github.com/swaggo/http-swagger"

	// "github.com/swaggo/http-swagger"
	"gopkg.in/yaml.v3"

	"configservergo/backend"

	// swagger docs generated by swaggo/swag
	_ "configservergo/docs"
)

func init() {
	_ = godotenv.Load()
}

type Config struct {
	Server        ServerConfig     `yaml:"server"`
	BackendConfig BackendConfigMap `yaml:"backend_config"`
}

type ServerConfig struct {
	Port  int          `yaml:"port"`
	Ssl   SslConfig    `yaml:"ssl"`
	Users []UserConfig `yaml:"users"`
}

type UserConfig struct {
	Username      string                     `yaml:"username"`
	Password      string                     `yaml:"password"`
	EncryptionKey string                     `yaml:"encryption_key"`
	Directory     string                     `yaml:"directory"`
	Backend       string                     `yaml:"backend"`
	Postgres      backend.PostgresUserConfig `yaml:"postgres"`
}

// UserBackend satisfies backend.UserBackend.
func (u *UserConfig) GetUsername() string      { return u.Username }
func (u *UserConfig) GetBackend() string       { return u.Backend }
func (u *UserConfig) GetPostgresDSN() string   { return u.Postgres.ConnectionString }
func (u *UserConfig) GetPostgresTable() string { return u.Postgres.TableName }

type BackendConfigMap struct {
	FileSystem FileSystemConfig              `yaml:"filesystem"`
	Git        GitConfig                     `yaml:"git"`
	Postgres   backend.PostgresBackendConfig `yaml:"postgres"`
}

type SslConfig struct {
	Enabled bool   `yaml:"enable"`
	Key     string `yaml:"key"`
	Cert    string `yaml:"cert"`
}

type FileSystemConfig struct {
	Directories []string `yaml:"directories"`
}

type GitConfig struct {
	Url string `yaml:"url"`
}

// Response structures for the GetValues endpoint.
type GetValuesResponse struct {
	Name            string           `json:"name"`
	Profiles        []string         `json:"profiles"`
	Label           *string          `json:"label"`
	Version         *string          `json:"version"`
	State           *string          `json:"state"`
	PropertySources []PropertySource `json:"propertySources"`
}

type PropertySource struct {
	Name   string                 `json:"name"`
	Source map[string]interface{} `json:"source"`
}

// ErrorResponse represents a standard error response.
type ErrorResponse struct {
	Description string `json:"description"`
	Status      string `json:"status"`
}

// App holds all dependencies for the HTTP server.
type App struct {
	Users   map[string]*UserConfig
	Backend *backend.Resolver
}

var (
	users                   = make(map[string]*UserConfig)
	supportedConfigFileType = []string{".properties", ".yml", ".yaml", ".json"}
	configFile              = flag.String("c", u.Getenv("CONFIG_FILE", "config.yaml"), "Config file to load")
	migrate                 = flag.Bool("migrate", true, "Run database migrations at startup")
)

func LoadConfig() Config {
	contentb := u.Must(os.ReadFile(*configFile))
	expandedContent := backend.ExpandEnvVars(string(contentb))

	var yamlobj Config
	err := yaml.Unmarshal([]byte(expandedContent), &yamlobj)
	if err != nil {
		fmt.Printf("Error parsing config file %s: %v\n", *configFile, err)
		os.Exit(1)
	}
	for _, user := range yamlobj.Server.Users {
		users[user.Username] = &user
	}

	return yamlobj
}

func main() {
	flag.Parse()
	appConfig := LoadConfig()

	// Build backend resolver.
	var fsBackend *backend.FileSystemBackend
	if len(appConfig.BackendConfig.FileSystem.Directories) > 0 {
		fsBackend = backend.NewFileSystemBackend(appConfig.BackendConfig.FileSystem.Directories[0])
	}

	pgBackend := backend.NewPostgresBackend(appConfig.BackendConfig.Postgres.DefaultConnectionString)

	resolver := backend.NewResolver(fsBackend, pgBackend)

	app := &App{
		Users:   users,
		Backend: resolver,
	}

	// Run migrations if requested.
	if *migrate {
		log.Println("[INFO] Running database migrations...")
		if err := migrateDB(appConfig.BackendConfig.Postgres.DefaultConnectionString); err != nil {
			log.Fatalf("[FATAL] Migration failed: %v", err)
		}
		log.Println("[INFO] Migrations complete.")
	}

	serverAddress := fmt.Sprintf(":%d", appConfig.Server.Port)
	if appConfig.Server.Ssl.Enabled {
		fmt.Printf("Starting HTTPS server on :%s\n", serverAddress)
		tlsConfig := &tls.Config{
			MinVersion: tls.VersionTLS12,
			CipherSuites: []uint16{
				tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
			},
		}
		server := &http.Server{
			Addr:      serverAddress,
			Handler:   app.Handler(),
			TLSConfig: tlsConfig,
		}
		log.Fatal(server.ListenAndServeTLS(appConfig.Server.Ssl.Cert, appConfig.Server.Ssl.Key))
	} else {
		fmt.Printf("Start server on port %s\n", serverAddress)
		log.Fatal(http.ListenAndServe(serverAddress, app.Handler()))
	}
}

// Handler returns the configured HTTP mux.
func (a *App) Handler() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /encrypt", basicAuth(a.encryptHandler))
	mux.HandleFunc("POST /decrypt", basicAuth(a.decryptHandler))
	mux.HandleFunc("POST /upload", basicAuth(a.uploadHandler))
	mux.HandleFunc("DELETE /delete", basicAuth(a.deleteHandler))
	mux.HandleFunc("GET /list", basicAuth(a.listHandler))
	mux.HandleFunc("GET /health", a.healthHandler)
	// Swagger UI
	mux.Handle("GET /swagger/{path...}", httpSwagger.Handler(
		httpSwagger.URL("/swagger/doc.json"), // This is bloody magic. The path is handled by httpSwagger in a non documented way
		// The load index.html also magic and the html fire JS script call to this endpoint
		// If u want to be served by itself then keep. Otherwise u need to set something listen on that path and service it
		// That is what I dont like this lib but nothing better so far.
	))
	mux.HandleFunc("GET /", basicAuth(a.getValuesHandler))
	return mux
}

func basicAuth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		username, password, ok := r.BasicAuth()
		if !ok {
			w.Header().Set("WWW-Authenticate", `Basic realm="ConfigServer Auth"`)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		user, exists := users[username]
		if !exists {
			w.Header().Set("WWW-Authenticate", `Basic realm="ConfigServer Auth"`)
			fmt.Fprintf(os.Stderr, "User '%s' does not exists\n", username)
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		if password != user.Password {
			w.Header().Set("WWW-Authenticate", `Basic realm="ConfigServer Auth"`)
			fmt.Fprintln(os.Stderr, "Password not matched")
			http.Error(w, "Unauthorized", http.StatusUnauthorized)
			return
		}
		r.Header.Set("X-Username", username)
		next(w, r)
	}
}

var cipherPattern = regexp.MustCompile(`[']{0,1}\{cipher\}[^}']+[']{0,1}`)

// Process cipher patterns in content.
func processCipherPatterns(content string, user *UserConfig) string {
	return cipherPattern.ReplaceAllStringFunc(content, func(match string) string {
		cipherData := strings.TrimPrefix(strings.TrimSuffix(match, "'"), "'")
		cipherData = strings.TrimPrefix(cipherData, "{cipher}")

		var decrypted string
		var err error

		if user.EncryptionKey != "" {
			// Symmetric encryption
			decrypted, err = u.Decrypt(cipherData, user.EncryptionKey, nil)
		} // TODO support asym decrypt?
		if err != nil {
			fmt.Printf("[ERROR] %s\nData: %s\n", err.Error(), cipherData)
			return "<n/a>"
		}
		return decrypted
	})
}

// migrateDB runs the CREATE TABLE IF NOT EXISTS migration for the postgres
// backend. Safe to call repeatedly — it is idempotent.
func migrateDB(dsn string) error {
	if dsn == "" {
		return fmt.Errorf("no postgres DSN configured — cannot run migrations")
	}
	pool, err := backend.NewPostgresBackend(dsn).CreateTempPool(dsn)
	if err != nil {
		return err
	}
	defer pool.Close()

	_, err = pool.Exec(context.Background(), backend.TableSQL)
	return err
}

// getValuesHandler processes the Spring Cloud Config GET request.
//
// URL variants supported:
//
//	/{app}-{profile}[-{label}].{ext}          → serve raw file bytes
//	/{app}/{profile}[-{label}]                 → serve as GetValuesResponse
//	/{full-file-path-without-ext}              → serve raw file by path
//
// See: https://docs.spring.io/spring-cloud-config/reference/server/serving-plain-text.html
//
// @Summary Retrieve application configuration
// @Description Fetch configuration for a Spring Cloud Config application.
// Supports multiple URL formats:
//   - GET /{app}/{profile} → Returns JSON GetValuesResponse (single profile)
//   - GET /{app}/{profile1},{profile2} → Returns merged JSON with both profiles
//   - GET /{app}/{profile}/{label} → Returns JSON GetValuesResponse with label
//   - GET /{app}-{profile}.{ext} → Returns raw file content
//   - GET /{full-path} → Returns raw file content by path
//
// Profiles are merged in order, with later profiles taking higher priority.
//
// @Tags Config
// @Accept json
// @Produce json
// @Param app path string true "Application name"
// @Param profile path string true "Profile name(s) - comma-separated for multiple profiles"
// @Param label path string false "Git label/branch (optional)"
// @Param ext path string false "File extension (.yaml, .json, .properties)"
// @Success 200 {object} GetValuesResponse "Configuration data returned as JSON"
// @Success 200 {file} application/octet-stream "Raw file content when requesting .ext format"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 404 {string} string "Config not found or file not found"
// @Failure 502 {string} string "Backend error"
// @Router /{app}/{profile} [get]
// @Router /{app}/{profile1},{profile2} [get]
// @Security BasicAuth
func (a *App) getValuesHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	be, err := a.Backend.ForUser(user)
	if err != nil {
		http.Error(w, fmt.Sprintf("backend error: %s", err), http.StatusBadGateway)
		return
	}

	path := r.URL.Path
	paths := strings.Split(path, "/")[1:] // first element is empty because path starts with /
	pathsLen := len(paths)

	switch {
	case pathsLen == 1:
		// Check if single path segment contains hyphen (app-profile format)
		if idx := strings.Index(paths[0], "-"); idx > 0 {
			app := paths[0][:idx]
			profile := paths[0][idx+1:]
			// Try serveValues first, fall back to raw file if not found
			a.serveValues(w, be, user, app, []string{profile}, "")
			return
		}
		serveFile(w, be, paths[0])
		return
	case pathsLen == 2:
		profiles := parseProfiles(paths[1])
		a.serveValues(w, be, user, paths[0], profiles, "")
		return
	case pathsLen == 3:
		label, _ := splitProfileAndExt(paths[2])
		profiles := parseProfiles(paths[1])
		a.serveValues(w, be, user, paths[0], profiles, label)
		return
	case pathsLen > 3:
		// Try to serve as a raw file. The last path segment is the filename.
		requestFileName := paths[pathsLen-1]
		serveFile(w, be, requestFileName)
		return
	}
}

// serveFile returns the raw bytes of a file from the backend.
func serveFile(w http.ResponseWriter, be backend.Backend, filename string) {
	data, err := be.GetFileByPath(filename)
	if backend.IsNotExist(err) {
		http.Error(w, "File not found", http.StatusNotFound)
		fmt.Printf("[ERROR] file not found: %s\n", filename)
		return
	}
	if err != nil {
		http.Error(w, "Error reading file", http.StatusInternalServerError)
		fmt.Printf("[ERROR] %s\n", err.Error())
		return
	}
	if _, err := w.Write(data); err != nil {
		http.Error(w, "Error", http.StatusInternalServerError)
		fmt.Printf("[ERROR] Sending data to client - %s\n", err.Error())
		return
	}
}

// serveValues returns a Spring Cloud Config GetValuesResponse JSON with multi-profile support.
//
// Profiles are processed in order, with later profiles taking higher priority.
// For each profile, the first matching extension is used (properties > yml > yaml > json).
// Multiple profiles are merged together.
func (a *App) serveValues(w http.ResponseWriter, be backend.Backend, user *UserConfig, app string, profiles []string, label string) {
	if len(profiles) == 0 {
		http.Error(w, "No profiles specified", http.StatusBadRequest)
		return
	}

	responseObj := GetValuesResponse{
		Name:            app,
		Profiles:        profiles,
		Label:           u.Ternary(label != "", &label, nil),
		PropertySources: []PropertySource{},
	}

	// For each profile, try extensions in priority order and take the first match
	allPropertySources := []PropertySource{}
	foundAny := false

	for _, profile := range profiles {
		profile, ext := splitProfileAndExt(profile)

		extensionsToTry := supportedConfigFileType
		if ext != "" {
			extensionsToTry = []string{ext}
		}

		// Find the first matching extension for this profile
		var matchedExt string
		var content []byte

		for _, fileExt := range extensionsToTry {
			data, err := be.GetFile(app, profile, label, fileExt)
			if backend.IsNotExist(err) {
				continue
			}
			if err != nil {
				log.Printf("[WARN] backend error for %s-%s-%s.%s: %v", app, profile, label, fileExt, err)
				continue
			}
			matchedExt = fileExt
			content = data
			break // First match wins
		}

		if matchedExt == "" {
			continue // No file found for this profile
		}

		// Parse and add to property sources
		parsedContent := string(content)
		parsedContent = processCipherPatterns(parsedContent, user)
		result := parseConfigData(parsedContent, matchedExt)

		sourceName := determineSourceName(be, app, profile, label, matchedExt)
		allPropertySources = append(allPropertySources, PropertySource{
			Name:   sourceName,
			Source: result,
		})
		foundAny = true
	}

	if !foundAny {
		http.Error(w, "Config not found", http.StatusNotFound)
		return
	}

	// Append individual property sources for each profile found
	responseObj.PropertySources = append(responseObj.PropertySources, allPropertySources...)

	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(responseObj)
}

// determineSourceName returns a descriptive name for a property source based on
// the backend type. This matches Spring Cloud Config's naming convention where
// the backend type is included in the source name.
func determineSourceName(be backend.Backend, app, profile, label, ext string) string {
	// Check if it's a filesystem backend
	if _, ok := be.(*backend.FileSystemBackend); ok {
		return fmt.Sprintf("FileSystemBackend app=%s profile=%s label=%s ext=%s", app, profile, label, ext)
	}
	// Default to postgres naming
	return fmt.Sprintf("postgres:config_server_files app=%s profile=%s label=%s ext=%s", app, profile, label, ext)
}

// splitProfileAndExt splits a string like "dev.yaml" into ("dev", ".yaml"), or
// "dev" into ("dev", ""). It is used by the GET handler to separate the profile
// name from its file extension.
func splitProfileAndExt(s string) (profile, ext string) {
	ext = filepath.Ext(s)
	profile = strings.TrimSuffix(s, ext)
	if ext == "" {
		return s, ""
	}
	return profile, ext
}

// parseConfigData parses raw config content into a flat key-value map.
func parseConfigData(content, ext string) map[string]interface{} {
	result := make(map[string]interface{})

	switch ext {
	case ".yaml", ".yml":
		var data interface{}
		if err := yaml.Unmarshal([]byte(content), &data); err == nil {
			FlatternDataToMap(data, "", result)
		}
	case ".json":
		var data interface{}
		if err := json.Unmarshal([]byte(content), &data); err == nil {
			FlatternDataToMap(data, "", result)
		}
	case ".properties":
		lines := strings.Split(content, "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if line != "" && !strings.HasPrefix(line, "#") && !strings.HasPrefix(line, "!") {
				parts := strings.SplitN(line, "=", 2)
				if len(parts) == 2 {
					result[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
				}
			}
		}
	}

	return result
}

// FlatternDataToMap flattens nested YAML/JSON into dot-notation keys.
func FlatternDataToMap(data interface{}, prefix string, result map[string]interface{}) {
	switch v := data.(type) {
	case map[string]interface{}:
		for key, value := range v {
			newKey := key
			if prefix != "" {
				newKey = prefix + "." + key
			}
			FlatternDataToMap(value, newKey, result)
		}
	case []interface{}:
		for i, value := range v {
			newKey := fmt.Sprintf("%s[%d]", prefix, i)
			FlatternDataToMap(value, newKey, result)
		}
	default:
		result[prefix] = v
	}
}

// encryptHandler encrypts plaintext with the authenticated user's key.
//
// @Summary Encrypt a value
// @Description Encrypts the provided plaintext using the authenticated user's encryption key.
// Returns the encrypted string directly in the response body.
//
// @Tags Encryption
// @Accept plain
// @Produce text/plain
// @Param body body string true "Plaintext to encrypt"
// @Success 200 {string} string "Encrypted ciphertext"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 400 {object} ErrorResponse "Bad request - invalid body or encryption failed"
// @Router /encrypt [post]
// @Security BasicAuth
func (a *App) encryptHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]

	content, err := io.ReadAll(r.Body)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Can not read request body", "status": "INVALID"})
		return
	}
	output, err := u.Encrypt(string(content), user.EncryptionKey, nil)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Can not encrypt", "status": "INVALID"})
		return
	}
	w.Write([]byte(output))
}

// decryptHandler decrypts a {cipher} value with the authenticated user's key.
//
// @Summary Decrypt a value
// @Description Decrypts the provided ciphertext using the authenticated user's encryption key.
// Returns the decrypted string directly in the response body.
//
// @Tags Encryption
// @Accept plain
// @Produce text/plain
// @Param body body string true "Ciphertext to decrypt"
// @Success 200 {string} string "Decrypted plaintext"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 400 {object} ErrorResponse "Bad request - invalid body or decryption failed"
// @Router /decrypt [post]
// @Security BasicAuth
func (a *App) decryptHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	content, err := io.ReadAll(r.Body)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Can not read request body", "status": "INVALID"})
		return
	}
	output, err := u.Decrypt(string(content), user.EncryptionKey, nil)
	if err != nil {
		log.Printf("[ERROR] %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{"description": "Text not encrypted with this key", "status": "INVALID"})
		return
	}
	w.Write([]byte(output))
}

// deleteHandler allows authenticated users to delete a config file.
//
// Query parameters:
//   - app (required)
//   - profile (required)
//   - label (optional)
//   - ext (required, defaults to .yaml)
//
// @Summary Delete a configuration file
// @Description Delete a configuration file for a specific app, profile, and optional label.
//
// @Tags Config
// @Produce application/json
// @Param app query string true "Application name" minlength(1) maxlength(64)
// @Param profile query string true "Profile name (e.g., dev, prod)" minlength(1) maxlength(64)
// @Param label query string false "Git label/branch" minlength(1) maxlength(64)
// @Param ext query string false "File extension" default(.yaml)
// @Success 200 {object} map[string]interface{} "File deleted successfully"
// @Failure 400 {object} ErrorResponse "Bad request - missing params or invalid input"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 404 {string} string "File not found"
// @Router /delete [delete]
// @Security BasicAuth
func (a *App) deleteHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	if user == nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Unauthorized",
			"status":      "INVALID",
		})
		return
	}

	// Parse query parameters
	app := r.URL.Query().Get("app")
	profile := r.URL.Query().Get("profile")
	label := r.URL.Query().Get("label")
	ext := r.URL.Query().Get("ext")
	if ext == "" {
		ext = ".yaml"
	}

	if app == "" || profile == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Missing required parameters: app, profile",
			"status":      "INVALID",
		})
		return
	}

	if !supportedFileExtension(ext) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Unsupported file extension: %s", ext),
			"status":      "INVALID",
		})
		return
	}

	if !validConfigPathSegment(app) || !validConfigPathSegment(profile) || !validConfigPathSegment(label) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Invalid app/profile/label. Only alphanumeric, hyphens, and underscores allowed",
			"status":      "INVALID",
		})
		return
	}

	be, err := a.Backend.ForUser(user)
	if err != nil {
		log.Printf("[ERROR] Failed to get backend for user %s: %s\n", user.Username, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadGateway)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Backend error",
			"status":      "INVALID",
		})
		return
	}

	if err := be.DeleteFile(app, profile, label, ext); err != nil {
		if backend.IsNotExist(err) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusNotFound)
			json.NewEncoder(w).Encode(map[string]any{
				"description": "File not found",
				"status":      "NOT_FOUND",
			})
			return
		}
		log.Printf("[ERROR] Failed to delete file for %s-%s-%s.%s: %s\n", app, profile, label, ext, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Failed to delete file: %s", err.Error()),
			"status":      "INVALID",
		})
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]any{
		"description": "File deleted successfully",
		"status":      "OK",
		"app":         app,
		"profile":     profile,
		"label":       label,
		"ext":         ext,
	})
}

// listHandler returns a list of all configuration files for the authenticated user.
//
// @Summary List all configuration files
// @Description Returns a list of all configuration files stored for the authenticated user.
//
// @Tags Config
// @Produce application/json
// @Success 200 {array} backend.Info "List of configuration files"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 502 {string} string "Backend error"
// @Router /list [get]
// @Security BasicAuth
func (a *App) listHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	if user == nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Unauthorized",
			"status":      "INVALID",
		})
		return
	}

	be, err := a.Backend.ForUser(user)
	if err != nil {
		log.Printf("[ERROR] Failed to get backend for user %s: %s\n", user.Username, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadGateway)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Backend error",
			"status":      "INVALID",
		})
		return
	}

	files, err := be.ListFiles()
	if err != nil {
		log.Printf("[ERROR] Failed to list files: %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Failed to list files: %s", err.Error()),
			"status":      "INVALID",
		})
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(files)
}

// uploadHandler allows authenticated users to deploy (store) their own config
// files. The request body is the raw file content.
//
// Supports two URL patterns:
//   - POST /{app}/{profile}.{ext}        — no label
//   - POST /{app}/{profile}-{label}.{ext} — with label
//
// The handler validates app/profile/label to prevent path traversal and only
// accepts supported file extensions.
//
// @Summary Upload configuration file
// @Description Upload a configuration file for a specific app, profile, and optional label.
// The request body must contain the raw file content.
//
// Supported URL patterns:
//   - POST /upload?app={app}&profile={profile}&ext={ext}          — no label
//   - POST /upload?app={app}&profile={profile}&label={label}&ext={ext} — with label
//
// @Tags Config
// @Accept plain
// @Produce application/json
// @Param app query string true "Application name" minlength(1) maxlength(64)
// @Param profile query string true "Profile name (e.g., dev, prod)" minlength(1) maxlength(64)
// @Param label query string false "Git label/branch" minlength(1) maxlength(64)
// @Param ext query string false "File extension (.yaml, .json, .properties)" default(.yaml)
// @Param body body string true "Raw configuration file content"
// @Success 200 {object} map[string]interface{} "File uploaded successfully"
// @Failure 400 {object} ErrorResponse "Bad request - missing params or invalid input"
// @Failure 401 {object} ErrorResponse "Unauthorized - invalid credentials"
// @Failure 403 {object} ErrorResponse "Forbidden - unsupported file extension"
// @Failure 500 {object} ErrorResponse "Internal server error - failed to store file"
// @Router /upload [post]
// @Security BasicAuth
func (a *App) uploadHandler(w http.ResponseWriter, r *http.Request) {
	user := a.Users[r.Header.Get("X-Username")]
	if user == nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusUnauthorized)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Unauthorized",
			"status":      "INVALID",
		})
		return
	}

	// Read the request body (raw file content)
	content, err := io.ReadAll(r.Body)
	if err != nil {
		log.Printf("[ERROR] Failed to read request body: %s\n", err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Can not read request body",
			"status":      "INVALID",
		})
		return
	}
	defer r.Body.Close()

	// Parse query parameters
	app := r.URL.Query().Get("app")
	profile := r.URL.Query().Get("profile")
	label := r.URL.Query().Get("label")

	if app == "" || profile == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Missing required parameters: app, profile",
			"status":      "INVALID",
		})
		return
	}

	// Determine extension
	ext := r.URL.Query().Get("ext")
	if ext == "" {
		ext = ".yaml" // default
	}

	// Validate app/profile/label
	if !validConfigPathSegment(app) || !validConfigPathSegment(profile) || !validConfigPathSegment(label) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Invalid app/profile/label. Only alphanumeric, hyphens, and underscores allowed",
			"status":      "INVALID",
		})
		return
	}

	// Validate extension
	if !supportedFileExtension(ext) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Unsupported file extension: %s", ext),
			"status":      "INVALID",
		})
		return
	}

	// Get backend for user
	be, err := a.Backend.ForUser(user)
	if err != nil {
		log.Printf("[ERROR] Failed to get backend for user %s: %s\n", user.Username, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadGateway)
		json.NewEncoder(w).Encode(map[string]any{
			"description": "Backend error",
			"status":      "INVALID",
		})
		return
	}

	// Store the file
	if err := be.PutFile(app, profile, label, ext, content); err != nil {
		log.Printf("[ERROR] Failed to upload file for %s-%s-%s.%s: %s\n", app, profile, label, ext, err.Error())
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]any{
			"description": fmt.Sprintf("Failed to upload file: %s", err.Error()),
			"status":      "INVALID",
		})
		return
	}

	// Success response
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	json.NewEncoder(w).Encode(map[string]any{
		"description": "File uploaded successfully",
		"status":      "OK",
		"app":         app,
		"profile":     profile,
		"label":       label,
		"ext":         ext,
	})
}

// parseUploadFilename parses a filename like "myapp-prod-staging.yaml" or
// "myapp-prod.yaml" into (app, profile, label).
func parseUploadFilename(filename string) (app, profile, label string) {
	// Remove extension
	name := strings.TrimSuffix(filename, filepath.Ext(filename))

	// Find the last hyphen to split profile from label
	lastHyphen := strings.LastIndex(name, "-")
	if lastHyphen == -1 {
		// No hyphen: treat entire name as app, no profile
		return name, "", ""
	}

	// Everything before the last hyphen is app
	app = name[:lastHyphen]
	// The part after the last hyphen contains profile[-label]
	rest := name[lastHyphen+1:]

	// Split rest into profile and optional label
	restParts := strings.Split(rest, "-")
	if len(restParts) >= 2 {
		// profile-label: restParts[0] is profile, restParts[1:] joined is label
		return app, restParts[0], strings.Join(restParts[1:], "-")
	}
	// profile only
	return app, rest, ""
}

// validConfigPathSegment validates that a string contains only safe characters
// for use in config paths (alphanumeric, hyphens, underscores).
func validConfigPathSegment(s string) bool {
	for _, c := range s {
		if !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
			(c >= '0' && c <= '9') || c == '-' || c == '_') {
			return false
		}
	}
	return true
}

// supportedFileExtension checks if the extension is one of the supported config
// file types.
func supportedFileExtension(ext string) bool {
	for _, supported := range supportedConfigFileType {
		if ext == supported {
			return true
		}
	}
	return false
}

// parseProfiles splits a comma-separated profile string into individual profiles.
// Examples: "dev" → ["dev"], "dev,common,production" → ["dev", "common", "production"]
func parseProfiles(profilesStr string) []string {
	profiles := strings.Split(profilesStr, ",")
	result := make([]string, 0, len(profiles))
	for _, p := range profiles {
		trimmed := strings.TrimSpace(p)
		if trimmed != "" {
			result = append(result, trimmed)
		}
	}
	return result
}

// healthHandler checks the health status of the server and its backends.
//
// Returns 200 OK if all checks pass, or 503 Service Unavailable if any check fails.
//
// @Summary Server health check
// @Description Checks the health status of the server and its configured backends.
//
// @Tags Health
// @Produce application/json
// @Success 200 {object} map[string]interface{} "Server is healthy"
// @Failure 503 {object} map[string]interface{} "Server is unhealthy"
// @Router /health [get]
func (a *App) healthHandler(w http.ResponseWriter, r *http.Request) {
	health := map[string]interface{}{
		"status": "UP",
		"checks": []map[string]interface{}{},
	}

	// Check backend resolver exists
	if a.Backend != nil {
		check := map[string]interface{}{
			"name":   "backend",
			"status": "UP",
		}
		health["checks"] = append(health["checks"].([]map[string]interface{}), check)
	}

	// Check database connectivity using actual configured DSN from users
	// Try to get the DSN from the first user's postgres config
	var pgDSN string
	for _, user := range a.Users {
		dsn := user.GetPostgresDSN()
		if dsn != "" {
			pgDSN = dsn
			break
		}
	}

	if pgDSN != "" {
		pool, err := backend.NewPostgresBackend(pgDSN).CreateTempPool(pgDSN)
		if err != nil {
			check := map[string]interface{}{
				"name":    "database",
				"status":  "DOWN",
				"details": err.Error(),
			}
			health["checks"] = append(health["checks"].([]map[string]interface{}), check)
			health["status"] = "DOWN"
		} else {
			pool.Close()
			check := map[string]interface{}{
				"name":   "database",
				"status": "UP",
			}
			health["checks"] = append(health["checks"].([]map[string]interface{}), check)
		}
	}

	w.Header().Set("Content-Type", "application/json")
	if health["status"] == "DOWN" {
		w.WriteHeader(http.StatusServiceUnavailable)
	} else {
		w.WriteHeader(http.StatusOK)
	}
	json.NewEncoder(w).Encode(health)
}
