// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/decrypt": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Decrypts the provided ciphertext using the authenticated user's encryption key.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Encryption"
                ],
                "summary": "Decrypt a value",
                "parameters": [
                    {
                        "description": "Ciphertext to decrypt",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Decrypted plaintext",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid body or decryption failed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/delete": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Delete a configuration file for a specific app, profile, and optional label.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Delete a configuration file",
                "parameters": [
                    {
                        "maxLength": 64,
                        "minLength": 1,
                        "type": "string",
                        "description": "Application name",
                        "name": "app",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 64,
                        "minLength": 1,
                        "type": "string",
                        "description": "Profile name (e.g., dev, prod)",
                        "name": "profile",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 64,
                        "minLength": 1,
                        "type": "string",
                        "description": "Git label/branch",
                        "name": "label",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": ".yaml",
                        "description": "File extension",
                        "name": "ext",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File deleted successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - missing params or invalid input",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "File not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/encrypt": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Encrypts the provided plaintext using the authenticated user's encryption key.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Encryption"
                ],
                "summary": "Encrypt a value",
                "parameters": [
                    {
                        "description": "Plaintext to encrypt",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Encrypted ciphertext",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid body or encryption failed",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/list": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Returns a list of all configuration files stored for the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "List all configuration files",
                "responses": {
                    "200": {
                        "description": "List of configuration files",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/backend.Info"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Backend error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Upload a configuration file for a specific app, profile, and optional label.",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Upload configuration file",
                "parameters": [
                    {
                        "maxLength": 64,
                        "minLength": 1,
                        "type": "string",
                        "description": "Application name",
                        "name": "app",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 64,
                        "minLength": 1,
                        "type": "string",
                        "description": "Profile name (e.g., dev, prod)",
                        "name": "profile",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maxLength": 64,
                        "minLength": 1,
                        "type": "string",
                        "description": "Git label/branch",
                        "name": "label",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": ".yaml",
                        "description": "File extension (.yaml, .json, .properties)",
                        "name": "ext",
                        "in": "query"
                    },
                    {
                        "description": "Raw configuration file content",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "File uploaded successfully",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad request - missing params or invalid input",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden - unsupported file extension",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - failed to store file",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{app}/{profile}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Fetch configuration for a Spring Cloud Config application.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Config"
                ],
                "summary": "Retrieve application configuration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Application name",
                        "name": "app",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Profile name (e.g., dev, prod, staging)",
                        "name": "profile",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Git label/branch (optional)",
                        "name": "label",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "File extension (.yaml, .json, .properties)",
                        "name": "ext",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Config not found or file not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Backend error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "backend.Info": {
            "type": "object",
            "properties": {
                "app": {
                    "type": "string"
                },
                "ext": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "modified": {
                    "type": "string"
                },
                "profile": {
                    "type": "string"
                }
            }
        },
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "main.GetValuesResponse": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "profiles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "propertySources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.PropertySource"
                    }
                },
                "state": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "main.PropertySource": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
